### ISSUE TITLE
服务端报错：io.netty.handler.codec.EncoderException: String too big

### ISSUE THREAD

**Issue by ph59x** [DancingSnow0517/MCDR-Command#10]
描述：
安装后正常开服，但玩家进入时必定被踢出，同时控制台报`io.netty.handler.codec.EncoderException: String too big`

环境：
系统：Debian 5.10.158-2 (2022-12-13) 5.10.0-20-amd64(debian11)
Java：[Alibaba Dragonwell 17.0.5.0.5+8](https://github.com/alibaba/dragonwell17/releases/tag/dragonwell-standard-17.0.5.0.5%2B8_jdk-17.0.5-ga)
Minecraft：1.19.3
Fabric：0.14.12
Fabric API：0.71.0
Cloth Config API：未安装，因1.1版本标注[“不再依赖 `cloth config api`”](https://github.com/DancingSnow0517/MCDR-Completion/commit/05d193afa400d77ea519d97dfd1a5c8d43d577a6)
Mod版本：1.2

日志输出：
(仅对玩家名和ip进行处理)
```
[Server] [22:56:41] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.12
[Server] [22:56:41] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[Server] [22:56:41] [main/INFO]: Loading 53 mods:
[Server]        - carpet 1.4.93
[Server]        - carpet-extra 1.4.91
[Server]        - carpet-tis-addition 1.44.0
[Server]        - com_moandjiezana_toml_toml4j 0.7.2 via fabricproxy-lite
[Server]        - conditional-mixin 0.3.2 via carpet-tis-addition
[Server]        - fabric-api 0.71.0+1.19.3
[Server]        - fabric-api-base 0.4.20+afca2f3e85 via fabric-api
[Server]        - fabric-api-lookup-api-v1 1.6.19+49abcf7e85 via fabric-api
[Server]        - fabric-biome-api-v1 12.1.0+b5d379b085 via fabric-api
[Server]        - fabric-block-api-v1 1.0.4+e022e5d185 via fabric-api
[Server]        - fabric-command-api-v1 1.2.20+f71b366f85 via fabric-api
[Server]        - fabric-command-api-v2 2.1.16+99f9db8085 via fabric-api
[Server]        - fabric-commands-v0 0.2.37+df3654b385 via fabric-api
[Server]        - fabric-containers-v0 0.1.46+df3654b385 via fabric-api
[Server]        - fabric-content-registries-v0 3.5.0+1d37d50285 via fabric-api
[Server]        - fabric-convention-tags-v1 1.2.1+8e4e694f85 via fabric-api
[Server]        - fabric-crash-report-info-v1 0.2.13+aeb40ebe85 via fabric-api
[Server]        - fabric-data-generation-api-v1 11.1.3+87855a7085 via fabric-api
[Server]        - fabric-dimensions-v1 2.1.40+48349a3f85 via fabric-api
[Server]        - fabric-entity-events-v1 1.5.6+b83334a085 via fabric-api
[Server]        - fabric-events-interaction-v0 0.4.39+3baeb27a85 via fabric-api
[Server]        - fabric-events-lifecycle-v0 0.2.41+df3654b385 via fabric-api
[Server]        - fabric-game-rule-api-v1 1.0.29+99f9db8085 via fabric-api
[Server]        - fabric-item-api-v1 2.1.7+e498f5f085 via fabric-api
[Server]        - fabric-item-group-api-v1 2.1.10+0a2a0d0b85 via fabric-api
[Server]        - fabric-lifecycle-events-v1 2.2.9+23a79c8a85 via fabric-api
[Server]        - fabric-loot-api-v2 1.1.19+75e9821185 via fabric-api
[Server]        - fabric-loot-tables-v1 1.1.23+9e7660c685 via fabric-api
[Server]        - fabric-message-api-v1 5.0.13+6ede1da985 via fabric-api
[Server]        - fabric-mining-level-api-v1 2.1.30+49abcf7e85 via fabric-api
[Server]        - fabric-networking-api-v1 1.2.16+4017a8cb85 via fabric-api
[Server]        - fabric-networking-v0 0.3.33+df3654b385 via fabric-api
[Server]        - fabric-object-builder-api-v1 5.3.0+85f102ee85 via fabric-api
[Server]        - fabric-particles-v1 1.0.19+f1e4495b85 via fabric-api
[Server]        - fabric-permissions-api-v0 0.1-SNAPSHOT via spark
[Server]        - fabric-registry-sync-v0 2.0.3+2608564685 via fabric-api
[Server]        - fabric-rendering-data-attachment-v1 0.3.24+afca2f3e85 via fabric-api
[Server]        - fabric-rendering-fluids-v1 3.0.17+f1e4495b85 via fabric-api
[Server]        - fabric-resource-conditions-api-v1 2.2.1+280be3ab85 via fabric-api
[Server]        - fabric-resource-loader-v0 0.10.4+a91e48b785 via fabric-api
[Server]        - fabric-screen-handler-api-v1 1.3.12+99f9db8085 via fabric-api
[Server]        - fabric-transfer-api-v1 2.1.13+f1e4495b85 via fabric-api
[Server]        - fabric-transitive-access-wideners-v1 2.3.0+5b9a588b85 via fabric-api
[Server]        - fabricloader 0.14.12
[Server]        - fabricproxy-lite 2.4.0
[Server]        - java 17
[Server]        - lithium 0.10.4
[Server]        - mcdrc 1.2+1.19.3
[Server]        - minecraft 1.19.3
[Server]        - nochatreports 1.19.3-v1.19.0
[Server]        - servux 0.1.0
[Server]        - spark 1.10.25
[Server]        - starlight 1.1.1+fabric.ae22326
[Server] [22:56:42] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/*****/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[Server] [22:56:42] [main/INFO]: Compatibility level set to JAVA_17
[Server] [22:56:42] [main/INFO]: Loaded configuration file for Lithium: 106 options available, 0 override(s) found
[Server] [22:56:46] [main/INFO]: Building unoptimized datafixer
[Server] [22:56:47] [TISCM Mapping/INFO]: Yarn mapping file yarn-1.19.3+build.5-v2.tiny loaded
[Server] [22:56:47] [main/INFO]: Mixing server.MixinServerGamePacketListenerImpl from nochatreports.mixins.json into net.minecraft.class_3244
[Server] [22:56:47] [main/INFO]: KONNICHIWA ZA WARUDO!
[Server] [22:56:47] [main/INFO]: Default JVM text encoding is: UTF-8
[Server] [22:56:47] [main/INFO]: Reading config file NoChatReports/NCR-Common.json...
[Server] [22:56:47] [main/INFO]: Writing config file NoChatReports/NCR-Common.json...
[Server] [22:56:47] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[Server] [22:56:48] [main/INFO]: Loaded 7 recipes
[Server] [22:56:49] [main/INFO]: Loaded 1179 advancements
[Server] [22:56:49] [main/INFO]: Mixing server.MixinDedicatedServer from nochatreports.mixins.json into net.minecraft.class_3176
[Server] [22:56:49] [main/INFO]: Mixing server.MixinPlayerList from nochatreports.mixins.json into net.minecraft.class_3324
[Server] [22:56:49] [main/INFO]: Mixing common.MixinServerStatus from nochatreports.mixins.json into net.minecraft.class_2926
[Server] [22:56:49] [main/INFO]: Applied 0 biome modifications to 0 of 63 new biomes in 1.087 ms
[Server] [22:56:49] [Server thread/INFO]: Starting minecraft server version 1.19.3
[Server] [22:56:49] [Server thread/INFO]: Loading properties
[Server] [22:56:49] [Server thread/INFO]: Default game type: SURVIVAL
[Server] [22:56:49] [Server thread/INFO]: Generating keypair
[Server] [22:56:49] [Server thread/INFO]: Starting Minecraft server on *:*****
[Server] [22:56:49] [Server thread/INFO]: Using epoll channel type
[Server] [22:56:49] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[Server] [22:56:49] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[Server] [22:56:49] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[Server] [22:56:49] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[Server] [22:56:49] [Server thread/INFO]: Preparing level "world"
[Server] [22:56:49] [Server thread/INFO]: [CM] Loaded 13 settings from carpet.conf
[Server] [22:56:50] [Netty Epoll Server IO #1/INFO]: Mixing server.MixinServerboundChatPacket from nochatreports.mixins.json into net.minecraft.class_2797
[Server] [22:56:50] [Netty Epoll Server IO #1/INFO]: Mixing server.MixinServerboundChatSessionUpdatePacket from nochatreports.mixins.json into net.minecraft.class_7861
[Server] [22:56:51] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[Server] [22:56:55] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[Server] [22:56:55] [Worker-Main-1/INFO]: Preparing spawn area: 27%
[Server] [22:56:56] [Worker-Main-1/INFO]: Preparing spawn area: 97%
[Server] [22:56:56] [Server thread/INFO]: Time elapsed: 4512 ms
[Server] [22:56:56] [Server thread/INFO]: Done (6.525s)! For help, type "help"
[Server] [22:57:01] [Server thread/INFO]: *****[/*****] logged in with entity id 27 at (-497.44707596962616, 130.1875, 385.4904642360194)
[Server] [22:57:01] [Server thread/INFO]: *****joined the game
[Server] [22:57:02] [Server thread/WARN]: Failed to handle packet for /*****
[Server] io.netty.handler.codec.EncoderException: String too big (was 33818 characters, max 32767)
[Server]        at net.minecraft.class_2540.method_10788(class_2540.java:666) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2540.method_10814(class_2540.java:661) ~[server-intermediary.jar:?]
[Server]        at cn.dancingsnow.mcdrc.networking.CommandNetwork.sendNodeDataToClient(CommandNetwork.java:19) ~[MCDR-Completion-1.2+1.19.3.jar:?]
[Server]        at net.minecraft.class_3244.handler$cjj002$onTick(class_3244.java:8979) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3244.method_18784(class_3244.java:330) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.handler$zbf000$modifiedRunLoop(MinecraftServer.java:3408) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:655) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[server-intermediary.jar:?]
[Server]        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[Server] [22:57:02] [Server thread/INFO]: ***** lost connection: Internal server error
[Server] [22:57:02] [Server thread/INFO]: *****left the game
[Server] [22:57:02] [Server thread/INFO]: *****[/*****] logged in with entity id 28 at (2896.43938697365, 113.0, 4136.051658695167)
[Server] [22:57:02] [Server thread/INFO]: ***** joined the game
[Server] [22:57:03] [Server thread/WARN]: Failed to handle packet for /*****
[Server] io.netty.handler.codec.EncoderException: String too big (was 33818 characters, max 32767)
[Server]        at net.minecraft.class_2540.method_10788(class_2540.java:666) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2540.method_10814(class_2540.java:661) ~[server-intermediary.jar:?]
[Server]        at cn.dancingsnow.mcdrc.networking.CommandNetwork.sendNodeDataToClient(CommandNetwork.java:19) ~[MCDR-Completion-1.2+1.19.3.jar:?]
[Server]        at net.minecraft.class_3244.handler$cjj002$onTick(class_3244.java:8979) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3244.method_18784(class_3244.java:330) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.handler$zbf000$modifiedRunLoop(MinecraftServer.java:3408) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:655) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[server-intermediary.jar:?]
[Server]        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[Server] [22:57:03] [Server thread/INFO]: ***** lost connection: Internal server error
[Server] [22:57:03] [Server thread/INFO]: ***** left the game
[Server] [22:57:25] [Netty Epoll Server IO #7/INFO]: Mixing common.MixinServerStatusSerializer from nochatreports.mixins.json into net.minecraft.class_2926$class_2929
[Server] [22:57:44] [Server thread/INFO]: *****[/*****] logged in with entity id 75 at (2896.43938697365, 113.0, 4136.051658695167)
[Server] [22:57:44] [Server thread/INFO]: ***** joined the game
[Server] [22:57:44] [Server thread/WARN]: Failed to handle packet for /*****
[Server] io.netty.handler.codec.EncoderException: String too big (was 33818 characters, max 32767)
[Server]        at net.minecraft.class_2540.method_10788(class_2540.java:666) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2540.method_10814(class_2540.java:661) ~[server-intermediary.jar:?]
[Server]        at cn.dancingsnow.mcdrc.networking.CommandNetwork.sendNodeDataToClient(CommandNetwork.java:19) ~[MCDR-Completion-1.2+1.19.3.jar:?]
[Server]        at net.minecraft.class_3244.handler$cjj002$onTick(class_3244.java:8979) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3244.method_18784(class_3244.java:330) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.handler$zbf000$modifiedRunLoop(MinecraftServer.java:3408) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:655) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[server-intermediary.jar:?]
[Server]        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[Server] [22:57:44] [Server thread/INFO]: ***** lost connection: Internal server error
[Server] [22:57:44] [Server thread/INFO]: ***** left the game
```

**Comment by ph59x** [comment]
补充环境：
MCDR v2.7.2
MCDRCommandExporter v1.1.0
Python 3.9.2

**Comment by ph59x** [comment]
补充：
无论客户端是否安装本mod均无法正常进入服务器，且报错内容相同。

**Comment by DancingSnow0517** [comment]
看起来是MCDR命令太多，导致一个网络包无法完全发送完全，溢出了，以后考虑下分包发送

**Comment by DancingSnow0517** [comment]
@ph59x 方便提供 `node.json` 用于测试吗？

**Comment by DancingSnow0517** [comment]
应该已经修复，可以移步到 [Github Action](https://github.com/DancingSnow0517/MCDR-Completion/actions/runs/4092603518) 下载测试。
